### ISSUE TITLE
How to change username/password?

### ISSUE THREAD

**Issue by mrquincle** [MJKoedam/crownstone-homey#4]
The settings for username / password disappeared. How does someone now change their password?

**Comment by MJKoedam** [comment]
When adding a device, a login view appears, the user can enter their credentials and continue selecting the devices to add.
When a user is already logged in, a confirmation view will be shown, where the user can choose to continue with their current credentials or log out so they can change their password.
The README.md shows how it looks like to the user.

**Comment by mrquincle** [comment]
I will add status information about this for the user to the settings page. They now don't have any means to know if a log in did fail.
